#! /bin/sh

### BEGIN INIT INFO
# Provides:		serialmanager
# Required-Start:	$local_fs $network
# Required-Stop:	$local_fs
# Default-Start:	2 3 4
# Default-Stop:		0 1 6
# Short-Description:	serialmanager
# Description:		serial port controller daemon
### END INIT INFO

start() {
    echo "starting serialmanager"
    cd /home/pi/PiMon
    pipenv run python serialManager.py
}

case "$1" in 

  start)
    start
  ;;

  stop)
    echo "stopping"
    sudo pkill -9 -f serialManager.py
  ;;

esac
exit 0
