#! /bin/sh

### BEGIN INIT INFO
# Provides:		<SERVICE NAME>
# Required-Start:	$local_fs $network
# Required-Stop:	$local_fs
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description:	<SERVICE NAME>
# Description:		<SERVICE DESCRIPTION>
### END INIT INFO

start() {
    echo "starting <SERVICE NAME>"
    <THE TERMINAL/BASH COMMANDS TO RUN THE SERVICE>
}

case "$1" in 

  start)
    start
  ;;

  stop)
    echo "stopping"
    sudo pkill -9 -f <THE FILE NAME>
  ;;

esac
exit 0
